"""empty message

Revision ID: 1cff8aa5fbb5
Revises: 7649d5f7803
Create Date: 2015-09-27 18:43:09.324986

"""

# revision identifiers, used by Alembic.
revision = '1cff8aa5fbb5'
down_revision = '7649d5f7803'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
