"""empty message

Revision ID: 2185c6c7b320
Revises: 1e345110f4ab
Create Date: 2015-09-27 18:45:59.590654

"""

# revision identifiers, used by Alembic.
revision = '2185c6c7b320'
down_revision = '1e345110f4ab'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_lists_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('link_list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_list_id'], ['link_list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('linkLists_users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkLists_users',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('link_list_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['link_list_id'], [u'link_list.id'], name=u'linkLists_users_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'linkLists_users_ibfk_2'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('link_lists_users')
    ### end Alembic commands ###
