"""empty message

Revision ID: 2a1c8dce1bbd
Revises: None
Create Date: 2015-08-31 18:14:04.110376

"""

# revision identifiers, used by Alembic.
revision = '2a1c8dce1bbd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_list_access_key', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_list_access_key')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('current_login_ip', sa.String(length=45), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_artist', sa.String(length=100), nullable=True),
    sa.Column('song_title', sa.String(length=200), nullable=True),
    sa.Column('song_url', sa.Text(), nullable=True),
    sa.Column('song_provider', sa.Text(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('link_list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_list_id'], ['link_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('link_list_subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('link_list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_list_id'], ['link_list.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('link_list_subscriber')
    op.drop_table('link')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('link_list')
    ### end Alembic commands ###
