"""empty message

Revision ID: 3aacee1d7e81
Revises: 2185c6c7b320
Create Date: 2015-09-28 17:02:37.943120

"""

# revision identifiers, used by Alembic.
revision = '3aacee1d7e81'
down_revision = '2185c6c7b320'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
