"""empty message

Revision ID: 3cbf1aa87250
Revises: 15c9109ff5ee
Create Date: 2015-11-02 18:13:01.644173

"""

# revision identifiers, used by Alembic.
revision = '3cbf1aa87250'
down_revision = '15c9109ff5ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_list', sa.Column('editable', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link_list', 'editable')
    ### end Alembic commands ###
