"""empty message

Revision ID: 54c558966178
Revises: None
Create Date: 2015-05-14 22:17:03.324948

"""

# revision identifiers, used by Alembic.
revision = '54c558966178'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_list_subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('link_list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_list_id'], ['link_list.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link_list_subscriber')
    ### end Alembic commands ###
