"""empty message

Revision ID: 56b9aa3c54ef
Revises: 218a0d9e0be0
Create Date: 2015-09-26 17:50:31.945719

"""

# revision identifiers, used by Alembic.
revision = '56b9aa3c54ef'
down_revision = '218a0d9e0be0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection')
    op.add_column('user', sa.Column('access_token', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('image_url', sa.String(length=512), nullable=True))
    op.add_column('user', sa.Column('provider_id', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'provider_id')
    op.drop_column('user', 'image_url')
    op.drop_column('user', 'access_token')
    op.create_table('connection',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('provider_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('provider_user_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('access_token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('secret', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('display_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('profile_url', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('image_url', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('rank', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'connection_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
