"""empty message

Revision ID: 7649d5f7803
Revises: 82b4b928f25
Create Date: 2015-09-26 17:58:13.511940

"""

# revision identifiers, used by Alembic.
revision = '7649d5f7803'
down_revision = '82b4b928f25'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_column('user', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'name')
    ### end Alembic commands ###
