"""empty message

Revision ID: 82b4b928f25
Revises: 56b9aa3c54ef
Create Date: 2015-09-26 17:55:51.005822

"""

# revision identifiers, used by Alembic.
revision = '82b4b928f25'
down_revision = '56b9aa3c54ef'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('provider', sa.String(length=255), nullable=True))
    op.drop_column('user', 'provider_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('provider_id', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'provider')
    ### end Alembic commands ###
